@Library('mysharedlibrarypractice')_
node('built-in')
{
    stage('contDownload')
    {
      cicd.newGit("https://github.com/krishnain/maven16.git")      
    }            
     stage('contBuild')               
    {         
       cicd.newMaven()  
    }  
 }
